project_id = "trlxxzessfbwvfvzkhff"

[functions.send-account-recovery]
verify_jwt = false

[functions.send-email-change-notification]
verify_jwt = false

[functions.start-conversation]
verify_jwt = true